name: Feature request
description: Suggest an idea for session-system.
title: "[Feature]: "
labels:
  - feature
  - needs-triage
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! Tell us what problem it solves and how it improves the project.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: As a caregiver, I need...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your proposed solution. Screenshots welcome.
      placeholder: Add a filter by age range on the sessions page...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other solutions did you consider and why were they not chosen?
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links to prior art, designs, or related issues.
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and discussions
          required: true
        - label: I am willing to help with implementation (optional)
          required: false