// Session types
export interface Session {
  id: string;
  name: string;
  description: string | null;
  year: number;
  sessionLocationId: string | null;
  location?: SessionLocation;
  sessionType?: string;
  ageLower: number | null;
  ageUpper: number | null;
  dayOfWeek: number | null;
  startTime: string | null;
  endTime: string | null;
  waitlist: boolean;
  capacity: number | null;
  whatToBring: string | null;
  prerequisites: string | null;
  photoAlbumUrl: string | null;
  internalNotes: string | null;
  archived: boolean;
  blockIds: string[];
}

export interface SessionLocation {
  id: string;
  name: string;
  address: string | null;
  region: string | null;
  lat: number | null;
  lng: number | null;
  instructions: string | null;
  contactName: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  internalNotes: string | null;
}

export interface SessionBlock {
  id: string;
  year: number;
  blockType: "term_1" | "term_2" | "term_3" | "term_4" | "special";
  name: string;
  startDate: string;
  endDate: string;
  timezone?: string;
}

export interface SchoolTerm {
  id: string;
  year: number;
  term: number;
  name: string;
  startDate: string;
  endDate: string;
  termBreakStart: string | null;
}

export interface ExclusionDate {
  id: string;
  year: number;
  date: string;
  reason: string | null;
}

// Signup types
export interface Signup {
  id: string;
  status: "pending" | "confirmed" | "waitlisted" | "withdrawn";
  createdAt: string;
  sessionId: string;
  childId: string;
  caregiverId: string;
  studentName: string;
  guardianName: string;
  email: string;
  phone: string | null;
}

// Attendance types
export interface AttendanceRoll {
  occurrence: Occurrence;
  items: AttendanceRollItem[];
}

export interface AttendanceRollItem {
  signupId: string;
  childId: string;
  childName: string;
  guardianName: string;
  attendance: AttendanceRecord | null;
}

export interface AttendanceRecord {
  id: string;
  occurrenceId: string;
  signupId: string;
  status: "present" | "absent_known" | "absent_unknown";
  notes: string | null;
  markedAt: string;
}

export interface AttendanceUpsert {
  signupId: string;
  status: "present" | "absent_known" | "absent_unknown";
  notes?: string;
}

// Occurrence types
export interface Occurrence {
  id: string;
  sessionId: string;
  startsAt: string;
  endsAt: string;
  cancelled: boolean;
  cancellationReason: string | null;
  autoGenerated: boolean;
  blockId: string | null;
  blockName: string | null;
}

export interface Staff {
  id: string;
  name: string;
  email: string;
  ssoId: string;
  active: boolean;
  lastLoginAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface StaffListItem {
  id: string;
  name: string;
  email: string;
  active: boolean;
}

export interface StaffSessionSummary {
  id: string;
  name: string;
  year: number;
  location: string | null;
}

export interface ChildDetails {
  id: string;
  caregiverId: string;
  name: string;
  dateOfBirth: string;
  mediaConsent: boolean;
  medicalInfo: string | null;
  otherInfo: string | null;
}

export interface ChildNote {
  id: string;
  childId: string;
  author: string | null;
  note: string;
}
