"""initial_setup

Revision ID: 7d1116be1b34
Revises:
Create Date: 2026-01-28 03:10:47.396850

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import (
    EncryptedString,
    EncryptedText,
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    StoredObject,
    PasswordHash,
    FernetBackend,
)
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID  # ty: ignore
sa.DateTimeUTC = DateTimeUTC  # ty: ignore
sa.ORA_JSONB = ORA_JSONB  # ty: ignore
sa.EncryptedString = EncryptedString  # ty: ignore
sa.EncryptedText = EncryptedText  # ty: ignore
sa.StoredObject = StoredObject  # ty: ignore
sa.PasswordHash = PasswordHash  # ty: ignore
sa.PasslibHasher = PasslibHasher  # ty: ignore
sa.PwdlibHasher = PwdlibHasher  # ty: ignore
sa.FernetBackend = FernetBackend  # ty: ignore
sa.PGCryptoBackend = PGCryptoBackend  # ty: ignore

# revision identifiers, used by Alembic.
revision = "7d1116be1b34"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "caregivers",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("referral_source", sa.String(length=255), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_caregivers")),
    )
    with op.batch_alter_table("caregivers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_caregivers_email"), ["email"], unique=True)

    op.create_table(
        "exclusion_dates",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exclusion_dates")),
        sa.UniqueConstraint("year", "date", name="uq_exclusion_dates_year_date"),
    )
    with op.batch_alter_table("exclusion_dates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exclusion_dates_date"), ["date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exclusion_dates_year"), ["year"], unique=False
        )

    op.create_table(
        "session_blocks",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("block_type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_blocks")),
        sa.UniqueConstraint("year", "block_type", name="uq_session_blocks_year_type"),
    )
    with op.batch_alter_table("session_blocks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_session_blocks_block_type"), ["block_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_session_blocks_year"), ["year"], unique=False
        )

    op.create_table(
        "session_locations",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("instructions", sa.String(length=500), nullable=True),
        sa.Column("contact_name", sa.String(length=255), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("internal_notes", sa.String(length=500), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_locations")),
    )
    op.create_table(
        "staff",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("sso_id", sa.String(length=255), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff")),
    )
    with op.batch_alter_table("staff", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_staff_active"), ["active"], unique=False)
        batch_op.create_index(batch_op.f("ix_staff_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_staff_sso_id"), ["sso_id"], unique=True)

    op.create_table(
        "caregiver_magic_links",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("caregiver_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["caregiver_id"],
            ["caregivers.id"],
            name=op.f("fk_caregiver_magic_links_caregiver_id_caregivers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_caregiver_magic_links")),
    )
    with op.batch_alter_table("caregiver_magic_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_caregiver_magic_links_caregiver_id"),
            ["caregiver_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_caregiver_magic_links_token_hash"),
            ["token_hash"],
            unique=True,
        )

    op.create_table(
        "caregiver_sessions",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("caregiver_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["caregiver_id"],
            ["caregivers.id"],
            name=op.f("fk_caregiver_sessions_caregiver_id_caregivers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_caregiver_sessions")),
    )
    with op.batch_alter_table("caregiver_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_caregiver_sessions_caregiver_id"),
            ["caregiver_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_caregiver_sessions_token_hash"), ["token_hash"], unique=True
        )

    op.create_table(
        "children",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("caregiver_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("media_consent", sa.Boolean(), nullable=False),
        sa.Column("medical_info", sa.String(length=1000), nullable=True),
        sa.Column("needs_devices", sa.Boolean(), nullable=False),
        sa.Column("other_info", sa.String(length=1000), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("ethnicity", sa.String(length=200), nullable=True),
        sa.Column("school_name", sa.String(length=200), nullable=True),
        sa.Column("gender", sa.String(length=100), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["caregiver_id"],
            ["caregivers.id"],
            name=op.f("fk_children_caregiver_id_caregivers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_children")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("session_location_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("session_type", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("age_lower", sa.Integer(), nullable=False),
        sa.Column("age_upper", sa.Integer(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("waitlist", sa.Boolean(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("what_to_bring", sa.Text(), nullable=True),
        sa.Column("prerequisites", sa.Text(), nullable=True),
        sa.Column("photo_album_url", sa.String(length=500), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(session_type = 'term' AND day_of_week IS NOT NULL) OR (session_type = 'special')",
            name=op.f("ck_sessions_ck_sessions_term_requires_schedule"),
        ),
        sa.CheckConstraint(
            "session_type IN ('term','special')",
            name=op.f("ck_sessions_ck_sessions_type"),
        ),
        sa.CheckConstraint(
            "day_of_week IS NULL OR day_of_week BETWEEN 0 AND 6",
            name=op.f("ck_sessions_ck_sessions_day_of_week_nullable"),
        ),
        sa.ForeignKeyConstraint(
            ["session_location_id"],
            ["session_locations.id"],
            name=op.f("fk_sessions_session_location_id_session_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sessions_archived"), ["archived"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_session_type"), ["session_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sessions_year"), ["year"], unique=False)

    op.create_table(
        "child_notes",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_child_notes_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_child_notes")),
    )
    with op.batch_alter_table("child_notes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_child_notes_child_id"), ["child_id"], unique=False
        )

    op.create_table(
        "session_block_links",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("block_id", sa.UUID(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["session_blocks.id"],
            name=op.f("fk_session_block_links_block_id_session_blocks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_block_links_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_block_links")),
        sa.UniqueConstraint(
            "session_id", "block_id", name="uq_session_block_links_session_block"
        ),
    )
    with op.batch_alter_table("session_block_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_session_block_links_block_id"), ["block_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_session_block_links_session_id"),
            ["session_id"],
            unique=False,
        )

    op.create_table(
        "session_occurrences",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "auto_generated",
            sa.Boolean(),
            nullable=False,
            comment="True if created by generate_occurrences, False if manually added",
        ),
        sa.Column(
            "block_id",
            sa.UUID(),
            nullable=True,
            comment="Which block this occurrence belongs to",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.CheckConstraint(
            "starts_at < ends_at",
            name=op.f("ck_session_occurrences_ck_session_occurrences_time_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["session_blocks.id"],
            name=op.f("fk_session_occurrences_block_id_session_blocks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_occurrences_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_occurrences")),
    )
    with op.batch_alter_table("session_occurrences", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_session_occurrences_block_id"), ["block_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_session_occurrences_session_id"),
            ["session_id"],
            unique=False,
        )

    op.create_table(
        "session_staff",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("staff_id", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_staff_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
            name=op.f("fk_session_staff_staff_id_staff"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_staff")),
        sa.UniqueConstraint("session_id", "staff_id", name="uq_session_staff"),
    )
    with op.batch_alter_table("session_staff", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_session_staff_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_session_staff_staff_id"), ["staff_id"], unique=False
        )

    op.create_table(
        "signups",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("caregiver_id", sa.UUID(), nullable=False),
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pickup_dropoff", sa.Text(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','confirmed','waitlisted','withdrawn')",
            name=op.f("ck_signups_ck_signups_status"),
        ),
        sa.ForeignKeyConstraint(
            ["caregiver_id"],
            ["caregivers.id"],
            name=op.f("fk_signups_caregiver_id_caregivers"),
        ),
        sa.ForeignKeyConstraint(
            ["child_id"], ["children.id"], name=op.f("fk_signups_child_id_children")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_signups_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signups")),
        sa.UniqueConstraint("session_id", "child_id", name="uq_signups_session_child"),
    )
    with op.batch_alter_table("signups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_signups_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_signups_status"), ["status"], unique=False)

    op.create_table(
        "attendance_audit_logs",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("occurrence_id", sa.UUID(), nullable=False),
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=True),
        sa.Column("old_status", sa.String(length=20), nullable=True),
        sa.Column("new_status", sa.String(length=20), nullable=True),
        sa.Column("old_reason", sa.Text(), nullable=True),
        sa.Column("new_reason", sa.Text(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_attendance_audit_logs_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["session_occurrences.id"],
            name=op.f("fk_attendance_audit_logs_occurrence_id_session_occurrences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_audit_logs")),
    )
    with op.batch_alter_table("attendance_audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attendance_audit_logs_child_id"), ["child_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_audit_logs_occurrence_id"),
            ["occurrence_id"],
            unique=False,
        )

    op.create_table(
        "attendance_records",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("occurrence_id", sa.UUID(), nullable=False),
        sa.Column("child_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('present','absent_known','absent_unknown')",
            name=op.f("ck_attendance_records_ck_attendance_records_status"),
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_attendance_records_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["session_occurrences.id"],
            name=op.f("fk_attendance_records_occurrence_id_session_occurrences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_records")),
    )
    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attendance_records_child_id"), ["child_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_records_occurrence_id"),
            ["occurrence_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_records_occurrence_id"))
        batch_op.drop_index(batch_op.f("ix_attendance_records_child_id"))

    op.drop_table("attendance_records")
    with op.batch_alter_table("attendance_audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_audit_logs_occurrence_id"))
        batch_op.drop_index(batch_op.f("ix_attendance_audit_logs_child_id"))

    op.drop_table("attendance_audit_logs")
    with op.batch_alter_table("signups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signups_status"))
        batch_op.drop_index(batch_op.f("ix_signups_session_id"))

    op.drop_table("signups")
    with op.batch_alter_table("session_staff", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_staff_staff_id"))
        batch_op.drop_index(batch_op.f("ix_session_staff_session_id"))

    op.drop_table("session_staff")
    with op.batch_alter_table("session_occurrences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_occurrences_session_id"))
        batch_op.drop_index(batch_op.f("ix_session_occurrences_block_id"))

    op.drop_table("session_occurrences")
    with op.batch_alter_table("session_block_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_block_links_session_id"))
        batch_op.drop_index(batch_op.f("ix_session_block_links_block_id"))

    op.drop_table("session_block_links")
    with op.batch_alter_table("child_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_child_notes_child_id"))

    op.drop_table("child_notes")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_year"))
        batch_op.drop_index(batch_op.f("ix_sessions_session_type"))
        batch_op.drop_index(batch_op.f("ix_sessions_archived"))

    op.drop_table("sessions")
    op.drop_table("children")
    with op.batch_alter_table("caregiver_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_caregiver_sessions_token_hash"))
        batch_op.drop_index(batch_op.f("ix_caregiver_sessions_caregiver_id"))

    op.drop_table("caregiver_sessions")
    with op.batch_alter_table("caregiver_magic_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_caregiver_magic_links_token_hash"))
        batch_op.drop_index(batch_op.f("ix_caregiver_magic_links_caregiver_id"))

    op.drop_table("caregiver_magic_links")
    with op.batch_alter_table("staff", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_staff_sso_id"))
        batch_op.drop_index(batch_op.f("ix_staff_email"))
        batch_op.drop_index(batch_op.f("ix_staff_active"))

    op.drop_table("staff")
    op.drop_table("session_locations")
    with op.batch_alter_table("session_blocks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_blocks_year"))
        batch_op.drop_index(batch_op.f("ix_session_blocks_block_type"))

    op.drop_table("session_blocks")
    with op.batch_alter_table("exclusion_dates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exclusion_dates_year"))
        batch_op.drop_index(batch_op.f("ix_exclusion_dates_date"))

    op.drop_table("exclusion_dates")
    with op.batch_alter_table("caregivers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_caregivers_email"))

    op.drop_table("caregivers")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
